### ISSUE TITLE
linting and standards question

### ISSUE THREAD

**Issue by mfrederickson** [codeforanchorage/courtbot#57]
I was wondering if we could include eslint and configure a standard for it? If so, which standard would it be?

Among other things I see some filenames are snake_case, camelCase, and nocase. A legacy problem I know, but consistency would be helpful.

**Comment by tescher** [comment]
I don't know much about eslint. Might want to post to the general channel
and see what you get.

Tim Escher
tim@eschers.com
608-432-5799

**Comment by mfrederickson** [comment]
I don't know what you mean by general channel-- what it that?

**Comment by tescher** [comment]
Sorry, the CodeforAnchorage #general Slack channel

Tim Escher
tim@eschers.com
608-432-5799

**Comment by mfrederickson** [comment]
Do I need an invitation to join that slack channel?

**Comment by tescher** [comment]
Send me your email address and I'll send you an invite

Tim Escher
tim@eschers.com
608 432 5799

On Sep 14, 2017 3:50 PM, "Marvin Frederickson" <notifications@github.com>
wrote:

Do I need an invitation to join that slack channel?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/codeforanchorage/courtbot/issues/57#issuecomment-329605116>,
or mute the thread
