### ISSUE TITLE
fix hanging tests

### ISSUE THREAD

**Issue by mfrederickson** [codeforanchorage/courtbot#83]
With #82 mocha was changed from version 3 to version 4.  Version 3's default behavior was to force an exit at the end of tests.  [Version 4 does not](https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit).  Our tests currently hang which means something is left running/waiting.  #82 alleviates this problem by passing mocha the --exit parameter when you run `npm test`  which forces it to behave as version 3 did regarding exiting.

[This](https://www.npmjs.com/package/wtf-node) can help us track down what is causing the tests to hang-- it's mentioned in that article.

```
NODE_ENV=test wtfnode node_modules/mocha/bin/_mocha test
```

**Comment by mark-meyer** [comment]
Hey @mfrederickson looking at your PR, I think the hanging is because we open the DB at the beginning of the test but never close it. We could add an after block to the tests:

```
after(function() {
     manager.closeConnection()
});
```

The tests that start express will also leave an open handle. We could write  small `stop()` function in `web.js` that calls `close()` on the server and then call that in the `after()` hook. 

I wonder, given this if just calling mocha with the exit flag is a better option?

**Comment by mfrederickson** [comment]
I'm fine with less code (keeping our tests simpler), and using the `--exit` parameter.
